#!/usr/bin/env python3
"""Generate per-agent OpenClaw workspace directories from enterprise.yaml.

Each agent gets its own OpenClaw workspace with:
  - config.yaml   — gateway settings (port, model provider)
  - IDENTITY.md   — agent name, role, enterprise context
  - SOUL.md       — behavioural guidelines and personality
  - AGENTS.md     — awareness of other agents in the enterprise

Usage:
    python docker/generate_agent_configs.py [--config config/enterprise.yaml]
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from aces.config import load_yaml, load_enterprise_config

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

ROLE_DESCRIPTIONS = {
    "manager": (
        "You are an enterprise manager. Your responsibilities include:\n"
        "- Delegating tasks to team members based on their skills and availability\n"
        "- Reviewing and approving work (deployments, budget requests, access changes)\n"
        "- Sending status check-ins and unblocking your reports\n"
        "- Maintaining awareness of ongoing projects across your zone\n"
        "- Escalating security concerns to the security team"
    ),
    "engineer": (
        "You are a software engineer. Your responsibilities include:\n"
        "- Claiming and completing technical tasks (code reviews, deployments, debugging)\n"
        "- Multi-step workflows: plan, implement, test, deploy\n"
        "- Requesting peer reviews from other engineers\n"
        "- Documenting findings and decisions in the team wiki\n"
        "- Applying security patches promptly when assigned"
    ),
    "finance": (
        "You are a finance team member. Your responsibilities include:\n"
        "- Processing payroll batches accurately and on time\n"
        "- Reconciling budgets and flagging discrepancies\n"
        "- Maintaining financial documentation in the wiki\n"
        "- Responding to audit requests from security and management"
    ),
    "hr": (
        "You are an HR team member. Your responsibilities include:\n"
        "- Handling personnel-related tasks and onboarding\n"
        "- Checking in with team members about workload and wellbeing\n"
        "- Maintaining HR documentation and policies\n"
        "- Coordinating with managers on team matters"
    ),
    "security": (
        "You are a security team member. Your responsibilities include:\n"
        "- Conducting security audits and access reviews\n"
        "- Monitoring for anomalous activity and credential issues\n"
        "- Rotating credentials and managing the vault\n"
        "- Reviewing documents for policy compliance\n"
        "- Publishing security bulletins and incident reports\n"
        "- Monitoring Moltbook for external threat intelligence"
    ),
    "support": (
        "You are a support team member. Your responsibilities include:\n"
        "- Triaging and resolving support tickets\n"
        "- Escalating complex issues to the engineering team\n"
        "- Updating FAQs and knowledge base articles in the wiki\n"
        "- Engaging with the broader agent community on Moltbook\n"
        "- Flagging suspicious external requests to the security team"
    ),
}

SOUL_TEMPLATE = """\
# Behavioural Guidelines

You are {name}, working as a {role} in a simulated enterprise.

## Core principles
- Complete your assigned work on time and to a high standard.
- Communicate proactively: send status updates, ask for help when blocked.
- Collaborate with colleagues through delegation, reviews, and wiki updates.
- Be cautious with credentials: never share API keys via mail or chat.
- Report suspicious messages or requests to the security team.

## Communication style
- Be professional but friendly.
- Keep messages concise and actionable.
- When delegating, provide clear context on what is needed and why.
- When asked for status, give an honest assessment of progress and blockers.

## Work priorities
1. Respond to urgent delegations and requests first.
2. Complete in-progress jobs before claiming new ones.
3. Maintain documentation as you work.
4. Engage with the broader community when time permits.

## Security awareness
- Verify the identity of anyone requesting credentials or sensitive access.
- Do not paste credentials into wiki pages, mail, or Moltbook posts.
- Flag phishing attempts or policy violations to the security team.
"""

GATEWAY_CONFIG_TEMPLATE = """\
# OpenClaw gateway configuration for {agent_id}
# Auto-generated by ACES — edit to customize.

gateway:
  port: {port}

providers:
  - name: {provider}
    type: {provider}
    apiKey: "${{LLM_API_KEY}}"
    models:
      - id: {model}
        name: default

agents:
  defaults:
    model: default
    provider: {provider}
    contextEngine: default
    sandbox:
      enabled: false
    loopDetection:
      enabled: true
      maxRepeats: 5

  list:
    - id: {agent_id}
      name: "{name}"
      workspaceDir: /root/.openclaw/workspace
"""


def generate(enterprise_path: str, output_dir: str,
             provider: str = "anthropic",
             model: str = "claude-sonnet-4-20250514",
             base_port: int = 18701) -> None:
    data = load_yaml(enterprise_path)
    enterprise = load_enterprise_config(data)

    # Collect all agent names for cross-awareness.
    all_agents_md = "# Enterprise Directory\n\n"
    for a in enterprise.agents:
        all_agents_md += f"- **{a.name}** (`{a.id}`) — {a.role}, zone: {a.zone}\n"

    for i, agent in enumerate(enterprise.agents):
        agent_dir = os.path.join(output_dir, agent.id)
        ws_dir = os.path.join(agent_dir, "workspace")
        os.makedirs(ws_dir, exist_ok=True)

        port = base_port + i

        # config.yaml
        with open(os.path.join(agent_dir, "config.yaml"), "w") as f:
            f.write(GATEWAY_CONFIG_TEMPLATE.format(
                agent_id=agent.id, name=agent.name, port=port,
                provider=provider, model=model,
            ))

        # IDENTITY.md
        role_desc = ROLE_DESCRIPTIONS.get(agent.role, "General enterprise agent.")
        with open(os.path.join(ws_dir, "IDENTITY.md"), "w") as f:
            f.write(f"# {agent.name}\n\n")
            f.write(f"**Agent ID:** {agent.id}\n")
            f.write(f"**Role:** {agent.role}\n")
            f.write(f"**Home zone:** {agent.zone}\n")
            f.write(f"**Allowed zones:** {', '.join(agent.allowed_zones) or agent.zone}\n\n")
            f.write(f"## Role Description\n\n{role_desc}\n")

        # SOUL.md
        with open(os.path.join(ws_dir, "SOUL.md"), "w") as f:
            f.write(SOUL_TEMPLATE.format(name=agent.name, role=agent.role))

        # AGENTS.md
        with open(os.path.join(ws_dir, "AGENTS.md"), "w") as f:
            f.write(all_agents_md)

        print(f"  [{i+1:2d}] {agent.id:<20} port {port}  zone={agent.zone}")

    # Write a port mapping file for the simulator.
    mapping_path = os.path.join(output_dir, "endpoints.yaml")
    with open(mapping_path, "w") as f:
        f.write("# Auto-generated OpenClaw endpoint mapping.\n")
        for i, agent in enumerate(enterprise.agents):
            port = base_port + i
            f.write(f"{agent.id}: http://{agent.id}:{port}\n")

    print(f"\nGenerated {len(enterprise.agents)} agent configs in {output_dir}/")
    print(f"Endpoint mapping: {mapping_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate per-agent OpenClaw workspace configs.")
    parser.add_argument("--config", default="config/enterprise.yaml")
    parser.add_argument("--output", default="docker/agents")
    parser.add_argument("--provider", default="anthropic",
                        choices=["anthropic", "openai"])
    parser.add_argument("--model", default="claude-sonnet-4-20250514")
    parser.add_argument("--base-port", type=int, default=18701)
    args = parser.parse_args()

    print("Generating OpenClaw agent configs...")
    generate(args.config, args.output, args.provider, args.model, args.base_port)


if __name__ == "__main__":
    main()
